name = "The Pandora's Box Pack"
author = "Will"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b24cbf519febd35bdcca8f93a3bd693e2edb3a75a175d738e6f3dd111d62272"

[versions]
forge = "40.1.85"
minecraft = "1.18.2"
