name = "UoP Unnamed Modpack"
author = "Will"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3befb23fd4993a9166a56c27d4fa222f5c3eb3011892ddfb329bc53caea06f13"

[versions]
forge = "40.1.85"
minecraft = "1.18.2"
