name = "The Pandora's Box Pack"
author = "Will"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "439aa33e1df56f69cd31c845d86fb86276b450245a34553ee331023e226a59db"

[versions]
forge = "40.1.85"
minecraft = "1.18.2"
