name = "The Pandora's Box Pack"
author = "Will"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e740366cbc7c9fdd2a262b9f98233914989f494b6b7a5900d07d5922d065a066"

[versions]
forge = "40.1.85"
minecraft = "1.18.2"
