name = "The Pandora's Box Pack"
author = "Will"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8c583d8ae634016d390a69dd9ae19bed62b5310f58ea10e0788f11ea3e45409"

[versions]
forge = "40.1.85"
minecraft = "1.18.2"
