name = "UoP Unnamed Modpack"
author = "Will"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "759fe9edce877b969d5569ae00120007e70bc772bff12a54f4201932fd160f88"

[versions]
forge = "40.1.85"
minecraft = "1.18.2"
